const SET_INVENTORY = "SET_INVENTORY";
const DELETE_INVENTORY_ITEM = "DELETE_INVENTORY_ITEM";
const ADD_INVENTORY_ITEM = "ADD_INVENTORY_ITEM";

export { SET_INVENTORY, DELETE_INVENTORY_ITEM, ADD_INVENTORY_ITEM };
